version: '2'
services:
  employee-management-mysql:
    image: mysql:5.7

    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306